#!/usr/bin/env python3
"""
EMOJI NEGOTIATION ENGLISH - $10,000 Negotiation Courses DESTROYED
Salary negotiation, business deals, persuasion, conflict resolution, getting what you want

The negotiation course scam:
- Negotiation training: $2,000-5,000+
- Sales/persuasion courses: $2,000-5,000+
- Conflict resolution training: $1,000-3,000+
- Executive negotiation coaching: $5,000-15,000+
- Mediation certification: $1,000-3,000+
- Total: $10,000-30,000+ for TECHNIQUES!

Emoji Negotiation English:
- Negotiation psychology decoded (how humans decide!)
- Salary negotiation mastery (get $10K-50K more!)
- Business deal tactics (close more deals!)
- Persuasion techniques (influence anyone!)
- Conflict resolution strategies (turn enemies to allies!)
- Power dynamics understanding (leverage decoded!)
- Objection handling (overcome any resistance!)
- Win-win frameworks (everyone happy!)
- $0, negotiation dominance!
"""

def negotiation_psychology():
    """Understand how humans make decisions"""
    print("="*70)
    print("🧠 NEGOTIATION PSYCHOLOGY - How Humans Really Decide")
    print("="*70)

    print("\n💡 THE BIG SECRET:")
    print("   Humans think they decide LOGICALLY")
    print("   Actually: Decide EMOTIONALLY, justify LOGICALLY")
    print("   💡 Win the emotion, logic follows!")

    print("\n" + "="*70)
    print("🎯 THE 6 PRINCIPLES OF INFLUENCE (Robert Cialdini)")
    print("="*70)

    print("\n1️⃣ RECIPROCITY (People repay favors)")
    print("   You give → They feel obligated to give back")
    print()
    print("   ✅ EXAMPLE:")
    print("   YOU: 'I can be flexible on timeline. Can you be flexible on price?'")
    print("   → You gave something, they want to reciprocate!")
    print()
    print("   💡 TACTIC: Give small concession FIRST")
    print("   They'll feel pressure to give back!")

    print("\n2️⃣ SCARCITY (People want what's limited)")
    print("   'Only X left' or 'Limited time' = urgency")
    print()
    print("   ✅ EXAMPLE:")
    print("   'I have another offer on the table. Need to decide by Friday.'")
    print("   → Creates urgency, they act faster!")
    print()
    print("   💡 TACTIC: Create deadline (real or implied)")
    print("   Scarcity = higher perceived value!")

    print("\n3️⃣ AUTHORITY (People trust experts)")
    print("   Credentials, experience, expertise = persuasive")
    print()
    print("   ✅ EXAMPLE:")
    print("   'In my 10 years doing this, here's what typically works...'")
    print("   → Establishes you know what you're talking about!")
    print()
    print("   💡 TACTIC: Show expertise early")
    print("   They'll trust your proposals!")

    print("\n4️⃣ CONSISTENCY (People want to be consistent)")
    print("   Once they commit to small thing, bigger things easier")
    print()
    print("   ✅ EXAMPLE:")
    print("   'You mentioned quality is important, right?'")
    print("   [They agree]")
    print("   'Then investing in the premium version makes sense.'")
    print("   → Used their own words against them (nicely!)")
    print()
    print("   💡 TACTIC: Get small 'yes' first")
    print("   Bigger 'yes' follows!")

    print("\n5️⃣ LIKING (People say yes to people they like)")
    print("   Similarity, compliments, cooperation = likability")
    print()
    print("   ✅ EXAMPLE:")
    print("   'I see you went to Michigan! Go Blue! I'm a Midwest person too.'")
    print("   → Find common ground, build rapport!")
    print()
    print("   💡 TACTIC: Find shared interests")
    print("   People negotiate favorably with friends!")

    print("\n6️⃣ SOCIAL PROOF (People follow what others do)")
    print("   'Everyone else is doing it' = powerful")
    print()
    print("   ✅ EXAMPLE:")
    print("   'Most companies in your industry pay $X for this role.'")
    print("   → Shows what's 'normal', they want to fit in!")
    print()
    print("   💡 TACTIC: Show what similar people chose")
    print("   They'll want to match!")

    print("\n" + "="*70)
    print("🎭 EMOTIONAL VS LOGICAL DECISION-MAKING")
    print("="*70)

    print("\n🧠 HOW IT REALLY WORKS:")
    print("   STEP 1: Emotion decides ('I want this!')")
    print("   STEP 2: Logic justifies ('Here's why it makes sense...')")
    print("   💡 Logic without emotion = no decision!")
    print("   💡 Emotion without logic = buyer's remorse!")

    print("\n✅ THE FORMULA:")
    print("   1. Appeal to EMOTION first (paint the vision!)")
    print("   2. Provide LOGIC second (justify the decision!)")

    print("\n✅ EXAMPLE (Selling Product):")
    print("   EMOTION: 'Imagine saving 10 hours per week. What would")
    print("            you do with that time?'")
    print("   LOGIC: 'Our software automates X, Y, Z processes.")
    print("           ROI is 300% in first year.'")
    print()
    print("   💡 Vision first, numbers second!")

    print("\n" + "="*70)
    print("⚓ ANCHORING EFFECT")
    print("="*70)

    print("\n💡 THE PRINCIPLE:")
    print("   First number mentioned = 'anchor'")
    print("   All other numbers judged relative to anchor")
    print("   💡 Control the anchor = control the negotiation!")

    print("\n✅ EXAMPLE (Salary Negotiation):")
    print("   ❌ THEM: 'What's your salary expectation?'")
    print("   ❌ YOU: '$80K'")
    print("   → You anchored LOW! They'll negotiate down from $80K!")
    print()
    print("   ✅ THEM: 'What's your salary expectation?'")
    print("   ✅ YOU: 'What's the budget for this role?'")
    print("   ✅ THEM: '$80-100K'")
    print("   ✅ YOU: 'Based on my experience, I'm targeting $110K.'")
    print("   → You anchored HIGH! They'll negotiate down from $110K!")

    print("\n💡 THE RULE:")
    print("   NEVER give first number in salary negotiation!")
    print("   If forced: Anchor HIGH (can always come down!)")
    print("   💡 First number = reference point for everything!")

    print("\n" + "="*70)
    print("🔄 THE CONTRAST PRINCIPLE")
    print("="*70)

    print("\n💡 THE PRINCIPLE:")
    print("   Humans judge by comparison, not absolute value")
    print("   Show expensive first → medium seems cheap!")

    print("\n✅ EXAMPLE (Pricing):")
    print("   'Our premium package is $10,000.'")
    print("   [Let that sink in]")
    print("   'Our standard package, which has most features, is $3,000.'")
    print("   → $3,000 seems CHEAP compared to $10,000!")
    print()
    print("   💡 High anchor makes real ask seem reasonable!")

    print("\n✅ EXAMPLE (Requests):")
    print("   BIG ASK: 'Can you have this done by tomorrow?'")
    print("   [They balk]")
    print("   REAL ASK: 'Okay, what about end of week?'")
    print("   → End of week seems easy compared to tomorrow!")
    print()
    print("   💡 Ask for more than you want first!")

    print("\n💡 GOLDEN RULE:")
    print("   Understanding psychology ≠ manipulation")
    print("   It's about FRAMING and COMMUNICATION")
    print("   Use ethically for win-win outcomes!")

def salary_negotiation_mastery():
    """Master salary negotiation - get what you're worth"""
    print("\n" + "="*70)
    print("💰 SALARY NEGOTIATION MASTERY - Get $10K-50K More!")
    print("="*70)

    print("\n💡 THE REALITY:")
    print("   NOT negotiating salary = leaving $1,000,000+ on table")
    print("   Over career (40 years)!")
    print("   💡 5 minutes of negotiation = life-changing money!")

    print("\n" + "="*70)
    print("🎯 THE GOLDEN RULES")
    print("="*70)

    print("\n🥇 RULE #1: NEVER GIVE NUMBER FIRST!")
    print("   THEM: 'What's your salary expectation?'")
    print()
    print("   ❌ WRONG: '$85,000'")
    print("   → You anchored! They'll negotiate DOWN from there!")
    print()
    print("   ✅ RIGHT:")
    print("   'I'd love to discuss compensation once we confirm I'm")
    print("    the right fit. What's the budgeted range for this role?'")
    print()
    print("   💡 Make THEM anchor first!")

    print("\n🥇 RULE #2: ANCHOR HIGH!")
    print("   If forced to give number:")
    print()
    print("   Research shows market rate: $80-100K")
    print("   ❌ DON'T SAY: '$90K' (middle of range)")
    print("   ✅ SAY: '$110-120K' (above range!)")
    print()
    print("   WHY? They negotiate DOWN")
    print("   Start high → End up at market rate")
    print("   Start middle → End up BELOW market!")

    print("\n🥇 RULE #3: NEGOTIATE TOTAL PACKAGE (Not just base!)")
    print("   Salary = only part of compensation!")
    print()
    print("   NEGOTIATE:")
    print("   💰 Base salary")
    print("   📈 Bonus/commission structure")
    print("   📊 Equity/stock options")
    print("   📅 PTO (vacation days)")
    print("   🏠 Remote work flexibility")
    print("   📚 Professional development budget")
    print("   🎓 Tuition reimbursement")
    print("   ✈️ Relocation assistance")
    print("   📱 Equipment/phone stipend")
    print("   💪 Gym membership")
    print()
    print("   💡 Can't budge on salary? Get more vacation!")

    print("\n🥇 RULE #4: NEVER ACCEPT FIRST OFFER!")
    print("   They EXPECT you to negotiate!")
    print("   First offer = testing the waters")
    print()
    print("   THEM: 'We'd like to offer you $85K'")
    print("   ❌ WRONG: 'Yes! I accept!'")
    print("   → Left money on table!")
    print()
    print("   ✅ RIGHT:")
    print("   'I'm excited about this opportunity! Based on my")
    print("    experience and market research, I was targeting")
    print("    $95-100K. Can we work together to get closer to that?'")
    print()
    print("   💡 They have room to move up!")

    print("\n" + "="*70)
    print("💬 THE NEGOTIATION CONVERSATION")
    print("="*70)

    print("\n📞 SCENARIO: They Make First Offer")
    print()
    print("   THEM: 'We'd like to offer $80K, 3 weeks PTO, standard benefits.'")
    print()
    print("   STEP 1: PAUSE & EXPRESS EXCITEMENT")
    print("   YOU: 'That's wonderful! I'm really excited about joining")
    print("        the team and making an impact on [specific project].'")
    print("   💡 Show enthusiasm BEFORE negotiating!")
    print()
    print("   STEP 2: THE THOUGHTFUL PAUSE")
    print("   YOU: [Pause 3 seconds]")
    print("        'I was hoping for something closer to market rate")
    print("         for this role and my experience level...'")
    print("   💡 Silence = discomfort. Let them feel it!")
    print()
    print("   STEP 3: ANCHOR YOUR NUMBER")
    print("   YOU: 'Based on my research and experience, I was targeting")
    print("        $95-100K. Is there flexibility to get closer to that?'")
    print("   💡 Specific range + question format = professional!")
    print()
    print("   STEP 4: WAIT FOR RESPONSE")
    print("   [SILENCE - Don't fill it!]")
    print("   They'll either:")
    print("   a) Counter higher")
    print("   b) Say they can't budge")
    print("   c) Ask what would make you happy")
    print()
    print("   STEP 5A: IF THEY COUNTER")
    print("   THEM: 'We can do $88K.'")
    print("   YOU: 'I appreciate you working with me! Can we split")
    print("        the difference at $92K?'")
    print("   💡 Always counter the counter!")
    print()
    print("   STEP 5B: IF THEY CAN'T BUDGE ON SALARY")
    print("   YOU: 'I understand salary is firm. Can we explore other")
    print("        parts of the package? I'd value extra PTO, professional")
    print("        development budget, or remote work flexibility.'")
    print("   💡 Total package negotiation!")

    print("\n" + "="*70)
    print("🎯 POWER PHRASES")
    print("="*70)

    print("\n💪 DEFLECT EARLY SALARY QUESTIONS:")
    print("   'I'd love to learn more about the role first. What's")
    print("    the budgeted range?'")
    print()
    print("   'I'm more focused on finding the right fit. What does")
    print("    the compensation package typically look like?'")
    print()
    print("   'I'm flexible! What range did you have in mind?'")

    print("\n💪 JUSTIFY YOUR NUMBER:")
    print("   'Based on market research for this role in [city], my")
    print("    X years of experience, and [specific skills], I'm")
    print("    targeting $X.'")
    print()
    print("   💡 Data + experience + skills = justification!")

    print("\n💪 HANDLE 'THAT'S ABOVE OUR BUDGET':")
    print("   'I understand. What IS the budget? Let's see if we can")
    print("    find a creative solution that works for both of us.'")
    print()
    print("   💡 Solution-oriented, not defensive!")

    print("\n💪 NEGOTIATE NON-SALARY:")
    print("   'If $X is firm, I'd love to discuss [vacation/remote/")
    print("    development budget]. Would adding [specific] be possible?'")
    print()
    print("   💡 Always have Plan B!")

    print("\n💪 GET IT IN WRITING:")
    print("   'This sounds great! Can you send over the formal offer")
    print("    letter with all comp details?'")
    print()
    print("   💡 Verbal ≠ binding!")

    print("\n" + "="*70)
    print("❌ SALARY NEGOTIATION KILLERS")
    print("="*70)

    print("\n❌ APOLOGIZING:")
    print("   'Sorry to ask, but...'")
    print("   'I hate to be difficult, but...'")
    print("   ✅ INSTEAD: Confident, direct asks!")

    print("\n❌ EMOTIONAL ARGUMENTS:")
    print("   'I really need $X because of my student loans...'")
    print("   'My rent is so expensive...'")
    print("   ✅ INSTEAD: Market value, skills, experience!")

    print("\n❌ ULTIMATUMS:")
    print("   'I need $X or I walk.'")
    print("   ✅ INSTEAD: Collaborative problem-solving!")

    print("\n❌ COMPARING TO COWORKERS:")
    print("   'I heard Sarah makes $X...'")
    print("   ✅ INSTEAD: Market data, your value!")

    print("\n❌ ACCEPTING TOO QUICKLY:")
    print("   First offer = always room to negotiate!")
    print("   ✅ INSTEAD: Thank, pause, counter!")

    print("\n💡 GOLDEN RULE:")
    print("   Worst they can say is 'No'")
    print("   Best outcome: $10K-50K more per year!")
    print("   💡 5 minutes of courage = life-changing money!")

def business_deal_tactics():
    """Close more deals, negotiate better terms"""
    print("\n" + "="*70)
    print("🤝 BUSINESS DEAL TACTICS - Close More, Better Terms")
    print("="*70)

    print("\n💡 THE SECRET:")
    print("   Business negotiation = relationship building")
    print("   Not combat, not war")
    print("   💡 Win-win > crushing them!")

    print("\n" + "="*70)
    print("📊 BATNA - Your Secret Weapon")
    print("="*70)

    print("\n🎯 BATNA = Best Alternative To Negotiated Agreement")
    print("   = What you'll do if deal falls through")
    print("   = Your POWER in negotiation!")

    print("\n✅ EXAMPLE:")
    print("   Negotiating with Client A for $50K project")
    print()
    print("   WEAK BATNA:")
    print("   'I have no other clients. I NEED this deal!'")
    print("   → They sense desperation, lowball you")
    print()
    print("   STRONG BATNA:")
    print("   'I have 2 other potential clients interested.'")
    print("   → You can walk away, they know it!")

    print("\n💡 THE RULE:")
    print("   ALWAYS develop alternatives BEFORE negotiating")
    print("   Never need ANY single deal")
    print("   💡 Options = power!")

    print("\n🎯 HOW TO BUILD STRONG BATNA:")
    print("   1. Have multiple opportunities in pipeline")
    print("   2. Research market rates")
    print("   3. Know your walk-away point")
    print("   4. Be willing to say 'No'")
    print()
    print("   💡 Best negotiators can walk away!")

    print("\n" + "="*70)
    print("🎭 THE NEGOTIATION DANCE")
    print("="*70)

    print("\n💃 PHASE 1: BUILD RAPPORT (Don't skip this!)")
    print("   Before numbers:")
    print("   - Small talk (find common ground)")
    print("   - Show genuine interest in them")
    print("   - Establish trust")
    print()
    print("   ✅ EXAMPLE:")
    print("   'Before we dive in, tell me about your company's goals")
    print("    for this year. What's most important to you?'")
    print()
    print("   💡 People negotiate better with friends!")

    print("\n💃 PHASE 2: UNDERSTAND THEIR NEEDS")
    print("   Ask questions:")
    print("   'What's your timeline?'")
    print("   'What's most important - price, quality, or speed?'")
    print("   'What would success look like?'")
    print()
    print("   💡 Understand before proposing!")

    print("\n💃 PHASE 3: ANCHOR (But Not Too Early!)")
    print("   After understanding needs:")
    print()
    print("   ✅ 'Based on scope, timeline, and deliverables, I'm")
    print("      proposing $X.'")
    print()
    print("   💡 Justify your number with their needs!")

    print("\n💃 PHASE 4: HANDLE OBJECTIONS")
    print("   THEM: 'That's more than we budgeted.'")
    print()
    print("   ✅ YOU: 'I understand. Help me understand your budget")
    print("           constraints. What number works for you?'")
    print()
    print("   [Listen]")
    print()
    print("   ✅ YOU: 'Okay, for that price point, here's what we")
    print("           can include: [reduced scope]. Would that work?'")
    print()
    print("   💡 Adjust scope, not just price!")

    print("\n💃 PHASE 5: TRADE, DON'T CAVE")
    print("   NEVER give concession without getting something back!")
    print()
    print("   ❌ WRONG:")
    print("   THEM: 'Can you do $45K instead of $50K?'")
    print("   YOU: 'Sure, okay.'")
    print("   → You lost $5K for nothing!")
    print()
    print("   ✅ RIGHT:")
    print("   THEM: 'Can you do $45K instead of $50K?'")
    print("   YOU: 'I can do $45K if we adjust timeline to 8 weeks")
    print("        instead of 6. Would that work?'")
    print("   → You gave up $5K, got 2 more weeks!")
    print()
    print("   💡 IF/THEN: 'If you want X, then I need Y'")

    print("\n💃 PHASE 6: CLOSE THE DEAL")
    print("   When you've agreed:")
    print()
    print("   ✅ 'Great! So we're aligned on $X, [terms], [timeline].")
    print("      I'll send over the contract today. When can you sign?'")
    print()
    print("   💡 Summarize + set clear next step!")

    print("\n" + "="*70)
    print("🧠 ADVANCED TACTICS")
    print("="*70)

    print("\n🎯 THE FLINCH:")
    print("   Physical reaction to their offer")
    print()
    print("   THEM: 'We can pay $30K'")
    print("   YOU: [Raise eyebrows, lean back, pause]")
    print("        'Oh... that's quite a bit lower than I expected.'")
    print()
    print("   → Makes them question their offer!")
    print("   💡 Body language speaks louder than words!")

    print("\n🎯 THE NIBBLE:")
    print("   Ask for small extra after main deal agreed")
    print()
    print("   After handshake:")
    print("   'Oh, one small thing - can you include X?'")
    print()
    print("   → They already mentally agreed, hard to say no to small ask!")
    print("   💡 Save small asks for end!")

    print("\n🎯 GOOD COP / BAD COP:")
    print("   (If negotiating with partner)")
    print()
    print("   PARTNER: 'No way. We can't do less than $60K.'")
    print("   YOU: 'I hear you, but let's see if we can find middle ground...")
    print("        Maybe $55K if we adjust scope?'")
    print()
    print("   → You look reasonable, they appreciate you!")
    print("   💡 One takes hard line, one finds compromise!")

    print("\n🎯 THE DEADLINE:")
    print("   Create urgency (ethically!)")
    print()
    print("   'I can hold this price through end of month. After that,")
    print("    our rates increase 15%.'")
    print()
    print("   → Motivates decision!")
    print("   💡 Scarcity = action!")

    print("\n🎯 SILENCE IS GOLDEN:")
    print("   After making offer:")
    print("   YOU: '[State price]'")
    print("   YOU: [SHUT UP]")
    print()
    print("   → Silence creates pressure!")
    print("   → They'll fill it (often with concession!)")
    print("   💡 Whoever speaks first after price = loses!")

    print("\n" + "="*70)
    print("📋 NEGOTIATION CHECKLIST")
    print("="*70)

    print("\n✅ BEFORE NEGOTIATION:")
    print("   ☐ Research market rates")
    print("   ☐ Know your BATNA (alternatives)")
    print("   ☐ Set walk-away point")
    print("   ☐ Prepare justification for your ask")
    print("   ☐ Anticipate their objections")

    print("\n✅ DURING NEGOTIATION:")
    print("   ☐ Build rapport first")
    print("   ☐ Ask questions (understand needs)")
    print("   ☐ Let THEM anchor if possible")
    print("   ☐ If you anchor, anchor HIGH")
    print("   ☐ Trade, don't cave (IF/THEN)")
    print("   ☐ Use silence strategically")
    print("   ☐ Never accept first offer")

    print("\n✅ AFTER AGREEMENT:")
    print("   ☐ Summarize terms aloud")
    print("   ☐ Get it in writing")
    print("   ☐ Set clear next steps")
    print("   ☐ Follow up quickly")

    print("\n💡 GOLDEN RULE:")
    print("   Win-win > win-lose")
    print("   Build relationship, not burn bridges")
    print("   💡 Today's negotiation = tomorrow's referral!")

def persuasion_techniques():
    """Influence anyone, get buy-in"""
    print("\n" + "="*70)
    print("🎯 PERSUASION TECHNIQUES - Influence Anyone")
    print("="*70)

    print("\n💡 THE DIFFERENCE:")
    print("   Manipulation = Win-lose (you trick them)")
    print("   Persuasion = Win-win (you show value)")
    print("   💡 Persuasion = ethical influence!")

    print("\n" + "="*70)
    print("🗣️ THE LANGUAGE OF PERSUASION")
    print("="*70)

    print("\n✅ USE 'YOU' (Not 'I'):")
    print("   ❌ 'I think this product is great'")
    print("   ✅ 'You'll save 10 hours per week with this'")
    print()
    print("   💡 Make it about THEM, not you!")

    print("\n✅ BECAUSE (Reason = Compliance):")
    print("   Study: Adding 'because' increases compliance 50%!")
    print()
    print("   ❌ 'Can I cut in line?'")
    print("   ✅ 'Can I cut in line because I'm late for meeting?'")
    print()
    print("   💡 Humans want reasons (even weak ones!)")

    print("\n✅ LOSS AVERSION (Fear > Gain):")
    print("   Humans fear losing MORE than they want to gain")
    print()
    print("   ❌ 'You'll gain $1,000 with this investment'")
    print("   ✅ 'You'll avoid losing $3,000 in taxes with this'")
    print()
    print("   💡 Frame as avoiding loss!")

    print("\n✅ SPECIFICITY = CREDIBILITY:")
    print("   ❌ 'Most people love this'")
    print("   ✅ '87% of users report satisfaction'")
    print()
    print("   💡 Specific numbers sound researched!")

    print("\n✅ RHETORICAL QUESTIONS:")
    print("   Instead of stating, ask")
    print()
    print("   ❌ 'You should buy this'")
    print("   ✅ 'Wouldn't you love to save 10 hours a week?'")
    print()
    print("   → They answer 'yes' mentally = buy-in!")
    print("   💡 Questions engage brain!")

    print("\n✅ RULE OF 3:")
    print("   Humans remember things in 3s")
    print()
    print("   'This solution is fast, affordable, and effective.'")
    print("   'We save you time, money, and headaches.'")
    print()
    print("   💡 3 reasons = persuasive!")

    print("\n" + "="*70)
    print("🎭 PERSUASION FRAMEWORKS")
    print("="*70)

    print("\n📝 FRAMEWORK #1: PROBLEM-AGITATE-SOLVE")
    print("   1. PROBLEM: Identify their pain")
    print("   2. AGITATE: Make pain visceral")
    print("   3. SOLVE: Present your solution")

    print("\n✅ EXAMPLE:")
    print("   PROBLEM: 'Hiring takes too long.'")
    print("   AGITATE: 'Every day a role stays open costs $500.")
    print("            That's $15,000/month wasted!'")
    print("   SOLVE: 'Our platform fills roles 60% faster.")
    print("          Save $10,000 per hire.'")
    print()
    print("   💡 Feel pain, then show relief!")

    print("\n📝 FRAMEWORK #2: BEFORE-AFTER-BRIDGE")
    print("   1. BEFORE: Current bad state")
    print("   2. AFTER: Desired good state")
    print("   3. BRIDGE: How to get there (your solution)")

    print("\n✅ EXAMPLE:")
    print("   BEFORE: 'You're spending 20 hours/week on admin tasks.'")
    print("   AFTER: 'Imagine spending those 20 hours on revenue work.'")
    print("   BRIDGE: 'Our automation handles admin so you can focus")
    print("           on what matters.'")
    print()
    print("   💡 Paint vision, then show path!")

    print("\n📝 FRAMEWORK #3: FEEL-FELT-FOUND")
    print("   1. FEEL: Acknowledge their concern")
    print("   2. FELT: Others had same concern")
    print("   3. FOUND: What they discovered")

    print("\n✅ EXAMPLE:")
    print("   FEEL: 'I understand you're worried about the learning curve.'")
    print("   FELT: 'Many of our clients felt the same way initially.'")
    print("   FOUND: 'What they found was most users are proficient")
    print("          in under a week.'")
    print()
    print("   💡 Validate → Normalize → Reassure!")

    print("\n" + "="*70)
    print("🧠 COGNITIVE BIASES TO LEVERAGE")
    print("="*70)

    print("\n🎯 CONFIRMATION BIAS:")
    print("   People seek info that confirms existing beliefs")
    print()
    print("   ✅ TACTIC: Find out what they believe, frame around it")
    print("   'You mentioned quality matters most. This premium")
    print("    option aligns perfectly with that.'")

    print("\n🎯 BANDWAGON EFFECT:")
    print("   People follow what others do")
    print()
    print("   ✅ TACTIC: Show social proof")
    print("   '500+ companies use this'")
    print("   'Most teams in your industry chose this'")

    print("\n🎯 ENDOWMENT EFFECT:")
    print("   People value what they already 'have'")
    print()
    print("   ✅ TACTIC: Free trial/demo")
    print("   Let them use it → they feel ownership → hard to give up!")

    print("\n🎯 DECOY EFFECT:")
    print("   Add third option to make target option look better")
    print()
    print("   ✅ TACTIC:")
    print("   Option A: $10 (basic)")
    print("   Option B: $50 (premium) ← want them to choose this")
    print("   Option C: $45 (premium minus one feature)")
    print("   → Option C makes B look like amazing value!")

    print("\n" + "="*70)
    print("💬 HANDLING RESISTANCE")
    print("="*70)

    print("\n🚧 'IT'S TOO EXPENSIVE':")
    print("   ❌ WRONG: 'No it's not!'")
    print("   ✅ RIGHT: 'I understand. Let's look at ROI...")
    print("            You spend $X on [problem]. This solution")
    print("            reduces that by 50%. Pays for itself in 3 months.'")
    print()
    print("   💡 Reframe as investment, not cost!")

    print("\n🚧 'I NEED TO THINK ABOUT IT':")
    print("   ❌ WRONG: 'Okay, bye!'")
    print("   ✅ RIGHT: 'Of course! What specific aspect do you")
    print("            want to think about? Maybe I can address that now.'")
    print()
    print("   → Often reveals real objection!")

    print("\n🚧 'I'M HAPPY WITH CURRENT SOLUTION':")
    print("   ❌ WRONG: 'But ours is better!'")
    print("   ✅ RIGHT: 'That's great! What do you love about it?'")
    print("            [Listen]")
    print("            'Makes sense. Here's one thing current solution")
    print("             doesn't do: [unique benefit]. Worth exploring?'")
    print()
    print("   💡 Validate, then differentiate!")

    print("\n💡 GOLDEN RULE:")
    print("   Persuasion = showing value")
    print("   Focus on THEIR needs, not YOUR product")
    print("   💡 Help them make good decision for themselves!")

def conflict_resolution():
    """Turn enemies into allies"""
    print("\n" + "="*70)
    print("⚔️ CONFLICT RESOLUTION - Turn Enemies Into Allies")
    print("="*70)

    print("\n💡 THE SECRET:")
    print("   Most conflicts come from misunderstanding")
    print("   Not malice, just miscommunication")
    print("   💡 Resolve conflict = build stronger relationship!")

    print("\n" + "="*70)
    print("🎯 THE CONFLICT RESOLUTION FRAMEWORK")
    print("="*70)

    print("\n📝 STEP 1: ACKNOWLEDGE EMOTION")
    print("   Don't go straight to logic!")
    print()
    print("   ✅ 'I can see you're frustrated. I get it.'")
    print("   ✅ 'I understand why you're upset.'")
    print()
    print("   💡 Validate feelings BEFORE problem-solving!")

    print("\n📝 STEP 2: LISTEN ACTIVELY")
    print("   Let them vent (don't interrupt!)")
    print()
    print("   Techniques:")
    print("   - 'Tell me more about that...'")
    print("   - 'What happened next?'")
    print("   - [Silence - let them talk]")
    print()
    print("   💡 People need to feel HEARD!")

    print("\n📝 STEP 3: REPEAT BACK (Mirror)")
    print("   Prove you heard them")
    print()
    print("   ✅ 'So if I'm hearing you correctly, you're upset")
    print("      because [summary]. Is that right?'")
    print()
    print("   → They feel understood!")
    print("   → You confirm actual issue!")

    print("\n📝 STEP 4: FIND COMMON GROUND")
    print("   What do you BOTH want?")
    print()
    print("   ✅ 'We both want this project to succeed, right?'")
    print("   ✅ 'I think we agree that [shared goal].'")
    print()
    print("   💡 Start with agreement, not disagreement!")

    print("\n📝 STEP 5: APOLOGIZE (If Appropriate)")
    print("   Even for misunderstanding")
    print()
    print("   ✅ 'I apologize for the miscommunication.'")
    print("   ✅ 'I'm sorry I didn't clarify that earlier.'")
    print()
    print("   💡 Apology ≠ weakness. Shows maturity!")

    print("\n📝 STEP 6: COLLABORATIVE PROBLEM-SOLVING")
    print("   'How can WE fix this?'")
    print()
    print("   ✅ 'What would a good solution look like for you?'")
    print("   ✅ 'Let's brainstorm options together.'")
    print()
    print("   💡 Us vs problem (not us vs each other!)")

    print("\n📝 STEP 7: AGREE ON ACTION")
    print("   Specific next steps")
    print()
    print("   ✅ 'So we're agreed: I'll [action] by [date], and")
    print("      you'll [action] by [date]. Sound good?'")
    print()
    print("   💡 Clear accountability!")

    print("\n" + "="*70)
    print("💬 CONFLICT CONVERSATION SCRIPTS")
    print("="*70)

    print("\n🗣️ SCENARIO: COWORKER ANGRY AT YOU")
    print()
    print("   THEM: 'You threw me under the bus in that meeting!'")
    print()
    print("   ❌ WRONG:")
    print("   'No I didn't! You're overreacting!'")
    print("   → Defensive, escalates conflict")
    print()
    print("   ✅ RIGHT:")
    print("   YOU: 'I can see why you'd feel that way. That wasn't")
    print("        my intention at all. Can you tell me what I said")
    print("        that came across that way?'")
    print("   [Listen]")
    print("   YOU: 'I understand. I should have been clearer that")
    print("        [context]. I'm sorry it came across differently.")
    print("        Let's make sure we're aligned going forward.'")
    print()
    print("   💡 Validate → Listen → Clarify → Apologize → Move forward!")

    print("\n🗣️ SCENARIO: DISAGREEMENT ON APPROACH")
    print()
    print("   THEM: 'Your approach won't work. We should do X instead.'")
    print()
    print("   ❌ WRONG:")
    print("   'My way is better!'")
    print("   → Ego battle")
    print()
    print("   ✅ RIGHT:")
    print("   YOU: 'Interesting. Help me understand your thinking on X.")
    print("        What advantages do you see?'")
    print("   [Listen]")
    print("   YOU: 'I see your point about [their advantage]. My concern")
    print("        with X is [specific concern]. What if we combine")
    print("        approaches: [hybrid solution]?'")
    print()
    print("   💡 Curious → Validate → Express concern → Collaborate!")

    print("\n🗣️ SCENARIO: SOMEONE BREAKS AGREEMENT")
    print()
    print("   Context: They missed deadline")
    print()
    print("   ❌ WRONG:")
    print("   'You're so unreliable! This always happens!'")
    print("   → Attack character, generalizations")
    print()
    print("   ✅ RIGHT:")
    print("   YOU: 'Hey, I noticed the report wasn't delivered Friday")
    print("        as we discussed. I'm concerned because [impact].")
    print("        What happened?'")
    print("   [Listen]")
    print("   YOU: 'I understand [their reason]. Going forward, if")
    print("        you're going to miss a deadline, can you let me")
    print("        know 24 hours in advance so we can adjust?'")
    print()
    print("   💡 Specific behavior → Impact → Listen → Future solution!")

    print("\n" + "="*70)
    print("🎭 DE-ESCALATION TECHNIQUES")
    print("="*70)

    print("\n✅ LOWER YOUR VOICE:")
    print("   They yell → you get quieter")
    print("   💡 Forces them to calm down to hear you!")

    print("\n✅ USE THEIR NAME:")
    print("   'Sarah, I hear you. Let's figure this out.'")
    print("   💡 Personalizes, breaks pattern!")

    print("\n✅ TAKE A BREAK:")
    print("   'I want to give this the attention it deserves.")
    print("    Can we revisit in 30 minutes?'")
    print("   💡 Cool-down period prevents escalation!")

    print("\n✅ FIND ONE THING TO AGREE ON:")
    print("   'We both want the project to succeed.'")
    print("   💡 Shifts from adversarial to collaborative!")

    print("\n✅ AVOID 'BUT':")
    print("   'I understand, BUT...' ← erases everything before 'but'!")
    print("   ✅ USE 'AND': 'I understand, AND here's my perspective...'")
    print("   💡 'And' doesn't negate their point!")

    print("\n" + "="*70)
    print("❌ CONFLICT MISTAKES")
    print("="*70)

    print("\n❌ GETTING DEFENSIVE:")
    print("   Immediately explaining/justifying")
    print("   ✅ INSTEAD: Listen first, explain second!")

    print("\n❌ MAKING IT PERSONAL:")
    print("   'You always...' 'You never...'")
    print("   ✅ INSTEAD: Focus on specific behavior!")

    print("\n❌ BRINGING UP PAST:")
    print("   'And another thing, last month you...'")
    print("   ✅ INSTEAD: Stay on current issue!")

    print("\n❌ MIND READING:")
    print("   'You did this because you don't respect me!'")
    print("   ✅ INSTEAD: Ask about intent!")

    print("\n❌ WINNING:")
    print("   Treating conflict as debate to win")
    print("   ✅ INSTEAD: Finding solution together!")

    print("\n💡 GOLDEN RULE:")
    print("   Conflict = opportunity")
    print("   Handled well → stronger relationship")
    print("   Handled poorly → burned bridge")
    print("   💡 Choose connection over being right!")

def summary():
    """Summarize negotiation mastery transformation"""
    print("\n" + "="*70)
    print("🎯 NEGOTIATION MASTERY SUMMARY")
    print("="*70)

    print("\n📊 BEFORE:")
    print("   😰 Afraid to negotiate")
    print("   💰 Accept first offer (leave $$ on table!)")
    print("   🤷 Don't know how to persuade")
    print("   ⚔️ Conflicts become disasters")
    print("   🎯 No strategy, just hope")
    print("   💸 Pay $10,000+ for training")

    print("\n✨ AFTER:")
    print("   ✅ Negotiate with confidence")
    print("   💰 Counter and get better deals")
    print("   🎯 Persuade effectively and ethically")
    print("   🤝 Resolve conflicts, build relationships")
    print("   🧠 Use psychology strategically")
    print("   🆓 $0 cost with this module!")

    print("\n" + "="*70)
    print("🔥 THE TECHNIQUES YOU LEARNED")
    print("="*70)

    print("\n🧠 NEGOTIATION PSYCHOLOGY:")
    print("   6 Principles: Reciprocity, Scarcity, Authority,")
    print("                 Consistency, Liking, Social Proof")
    print("   Anchoring Effect: First number = reference point")
    print("   Emotion → Decision, Logic → Justification")

    print("\n💰 SALARY NEGOTIATION:")
    print("   NEVER give number first!")
    print("   Anchor HIGH (can always come down!)")
    print("   Negotiate total package (not just base!)")
    print("   NEVER accept first offer!")
    print("   💡 5 minutes = $10K-50K more!")

    print("\n🤝 BUSINESS DEALS:")
    print("   BATNA = your power (alternatives!)")
    print("   Build rapport → Understand → Anchor → Trade")
    print("   IF/THEN: Never give without getting")
    print("   Silence = pressure (use it!)")

    print("\n🎯 PERSUASION:")
    print("   Use 'YOU' not 'I' (about them!)")
    print("   'Because' = +50% compliance")
    print("   Loss aversion > gain (avoid losing!)")
    print("   Problem-Agitate-Solve framework")

    print("\n⚔️ CONFLICT RESOLUTION:")
    print("   Acknowledge emotion → Listen → Mirror → Common ground")
    print("   Apologize if appropriate → Collaborate → Action")
    print("   De-escalate: Lower voice, use name, take break")

    print("\n" + "="*70)
    print("💰 VALUE DESTROYED")
    print("="*70)

    print("\n💸 THEY CHARGE:")
    print("   Negotiation training: $2,000-5,000")
    print("   Sales/persuasion courses: $2,000-5,000")
    print("   Conflict resolution: $1,000-3,000")
    print("   Executive coaching: $5,000-15,000")
    print("   ──────────────────────────────")
    print("   TOTAL: $10,000-30,000+")

    print("\n🆓 WE PROVIDE:")
    print("   Complete negotiation psychology")
    print("   Salary negotiation mastery")
    print("   Business deal tactics")
    print("   Persuasion techniques")
    print("   Conflict resolution frameworks")
    print("   All scripts and formulas")
    print("   ──────────────────────────────")
    print("   TOTAL: $0")

    print("\n" + "="*70)
    print("🚀 THE REVOLUTION")
    print("="*70)

    print("\n💡 TRADITIONAL COURSES:")
    print("   'Negotiation is an art...'")
    print("   'It takes years to master...'")
    print("   'Natural talent required...'")
    print("   'Pay $10,000+ for secrets...'")

    print("\n⚡ EMOJI NEGOTIATION MASTERY:")
    print("   Negotiation has FORMULAS")
    print("   Psychology = learnable")
    print("   Scripts = reusable")
    print("   Anyone can master it")
    print("   💡 Learn today, use tomorrow!")

    print("\n" + "="*70)
    print("🎯 YOUR TRANSFORMATION")
    print("="*70)

    print("\n🤝 NOW YOU CAN:")
    print("   ✅ Negotiate salary (get $10K-50K more!)")
    print("   ✅ Close business deals (better terms!)")
    print("   ✅ Persuade ethically (show value!)")
    print("   ✅ Resolve conflicts (build relationships!)")
    print("   ✅ Understand psychology (leverage it!)")
    print("   ✅ Never accept first offer (always counter!)")
    print("   ✅ Build strong BATNA (have options!)")
    print("   ✅ Use silence strategically (power move!)")

    print("\n🔥 NEGOTIATION IS NO LONGER SCARY!")
    print("   It's psychology + scripts + practice")
    print("   You learned all the techniques")
    print("   For $0")

    print("\n" + "="*70)
    print("🖤 THE BLACKROAD WAY")
    print("="*70)

    print("\n✂️ CUT THE GATEKEEPING:")
    print("   No $10,000 training needed")
    print("   No 'natural negotiator' myth")
    print("   Just psychology and scripts")

    print("\n🎨 MAKE IT VISUAL:")
    print("   See the frameworks")
    print("   Follow the formulas")
    print("   Copy the scripts")

    print("\n🧠 SHOW UNDERSTANDING:")
    print("   WHY psychology works")
    print("   WHY anchoring matters")
    print("   WHY silence is powerful")

    print("\n🌍 $0 ACCESSIBLE:")
    print("   Complete negotiation mastery")
    print("   All scripts included")
    print("   No hidden costs")

    print("\n" + "="*70)
    print("💬 FINAL WORD")
    print("="*70)

    print("\n🎯 Negotiation courses charge $10,000+ for techniques.")
    print("   We gave you all the techniques. For $0.")

    print("\n💰 One salary negotiation = ROI of 1,000X on $0.")
    print("   $10K-50K more for 5 minutes of courage.")

    print("\n💡 Psychology > Guessing")
    print("   Scripts > Winging it")
    print("   $0 > $10,000")

    print("\n🔥 Case closed. 🖤🛣️")

def main():
    """Run complete negotiation mastery course"""
    print("\n" + "="*70)
    print("🤝 EMOJI NEGOTIATION ENGLISH")
    print("Destroy $10,000 Negotiation Courses in 1 Hour")
    print("="*70)

    print("\n💡 THE NEGOTIATION COURSE SCAM:")
    print("   Executive negotiation coaching: $15,000+")
    print("   Sales training courses: $5,000+")
    print("   They teach you PSYCHOLOGY and SCRIPTS")
    print("   We're giving you ALL the techniques")
    print("   For $0")
    print("   🔥 Let's destroy the negotiation industry! 🔥")

    input("\n🧠 Press ENTER to master negotiation psychology...")
    negotiation_psychology()

    input("\n💰 Press ENTER to master salary negotiation...")
    salary_negotiation_mastery()

    input("\n🤝 Press ENTER to learn business deal tactics...")
    business_deal_tactics()

    input("\n🎯 Press ENTER to master persuasion...")
    persuasion_techniques()

    input("\n⚔️ Press ENTER to master conflict resolution...")
    conflict_resolution()

    input("\n🎯 Press ENTER for final summary...")
    summary()

    print("\n" + "="*70)
    print("🔥 NEGOTIATION MASTERY COMPLETE!")
    print("="*70)
    print("\n🤝 You can now:")
    print("   ✅ Negotiate salary like a pro ($10K-50K more!)")
    print("   ✅ Close business deals with better terms")
    print("   ✅ Persuade anyone ethically and effectively")
    print("   ✅ Resolve conflicts and build relationships")
    print("   ✅ Understand and leverage psychology")
    print("   ✅ Never leave money on the table again")
    print("\n💰 Value received: $10,000-30,000+")
    print("💸 Amount paid: $0")
    print("\n🖤🛣️ BlackRoad: Cut the gatekeeping. Democratize knowledge.")
    print("\n🔥 The negotiation industry has been EXPOSED! 🔥\n")

if __name__ == "__main__":
    main()
